- README.md
- package.json
- snippets/snippets.json
> add code snippets

- lib/utilities.js
> run playbook on mac

- extension.js
> add null check for playbook file

- extension.js
- lib/utilities.js
- package.json
run ansible commands from command palette. @zikalino
> run ansible commands from command palette

- test/extension.test.js
add one more test case. @zikalino
> add one more test

- extension.js
- lib/ansibleRunner.js
- lib/terminalExecutor.js
- lib/utilities.js
- package.json
add terminal support to start ansible docker. @zikalino
> add terminal support to start ansible docker

- extension.js
- lib/ansibleRunner.js
- package.json
just spelling mistake and actually adding command in the menu
> some fixes related to terminal

- config/credentials.yml
- package.json
- src/ansibleRunner.ts
- src/extension.ts
- src/utilities.ts
read credential from yml file, while yml file format is template. yml file path is configurable in settings.json
> checkin credential file config

- package.json
- src/cloudConsole.ts
- src/constants.ts
- src/telemetryClient.ts
- src/terminalExecutor.ts
- src/terminalRunner.ts
- src/utilities.ts
fix hardcode timeout after terminal Init cmd, but callback.
> fix hardcode timeout after terminal Init cmd

- snippets/snippets.json
updated azure snippets:
- fixed formatting so yaml can be parsed properly
> fixed azure snippet formatting

- docker/Dockerfile
> add dockerfile

- src/cloudConsole.ts
- src/constants.ts
1. escape quotes in playbook when send to cloudshell
2. use official release ansible docker image
> bug fixing

- README.md
- scripts/generate_codesnippets.ts
- snippets/codesnippets.json
- src/cloudShellRunner.ts
- src/terminalRunner.ts
- src/utilities.ts
how to disable telemetry collecting
> add disable telemetry setting

- src/terminalExecutor.ts
terminal not showing when run commands again
> fix bugs in testing on ubuntu

- README.md
- src/cloudConsole.ts
- src/completionEngine.ts
- src/terminalExecutor.ts
- src/terminalRunner.ts
refine docs and code formatting before release
> refine docs, code formatting

- README.md
- package-lock.json
- package.json
- src/SSHConsole.ts
- src/SSHLauncher.ts
- src/cloudShellRunner.ts
- src/extension.ts
- src/interfaces.ts
- src/sshRunner.ts
- src/terminalExecutor.ts
- src/utilities.ts
support run playbook via ssh remotely
> support ssh

- .gitignore
- README.md
- package-lock.json
- package.json
- server/package-lock.json
- server/package.json
- server/src/server.ts
- server/src/services/yamlDocumentSymbol.ts
- server/src/services/yamlHover.ts
- server/src/yamlLanguageService.ts
- server/tsconfig.json
- src/ansibleCompletionItemProvider.ts
- src/completionEngine.ts
- src/extension.ts
- src/sshRunner.ts
- src/utilities.ts
- syntaxes/Ansible.tmLanguage
below features supported in language server:
1. symbols
2. hover on module names to show documentation link
add new feature in auto-completion to auto complete variables.
some todo:
1. move auto-complete into language server.
how language server implemented:
1. based on npm package vscode-yaml-languageservices.
> setup language server

- CHANGELOG.md
- README.md
- package.json
- src/cloudConsoleLauncher.ts
- src/cloudShellRunner.ts
- src/constants.ts
- src/dockerRunner.ts
- src/sshRunner.ts
- src/utilities.ts
1. check node installed before run ssh
2. for cloudshell usage promopt, add 'not show this again' ability
3. cloudshell connection keepalive
> check node installed before run ssh

- src/dockerRunner.ts
> fix docker volume map when path contains whitespace

- README.md
add how to contribute docs
doc update
> add how to contribute

- README.md
- package.json
- server/package-lock.json
- server/package.json
- server/src/server.ts
- server/src/services/yamlDocumentSymbol.ts
- server/src/services/yamlHover.ts
- server/src/yamlLanguageService.ts
- src/ansibleCompletionItemProvider.ts
- src/cloudConsole.ts
- src/cloudShellRunner.ts
- src/completionData.ts
- src/completionEngine.ts
refine code snippet implementation, so it will be part of auto-completion, no need to click `ctrl + space`
- Bug fixing, Issue #90
> refine code snippet to skip ctrl + space

- package.json
- src/extension.ts
temporarily disable it, will enable it later.
- New Feature
- Bug fixing
> temporary disable azure_rm_deployment

- README.md
- src/ansibleCompletionItemProvider.ts
- src/cloudConsole.ts
- src/cloudShellRunner.ts
- src/extension.ts
- src/sshRunner.ts
- src/utilities.ts
add option "Add New Option" to ssh server drop down list. to save user's effort to switch from vscode to config file editing.
- New Feature
- Bug fixing
> add new host in ssh

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/azureStorageHelper.ts
- src/cloudConsole.ts
- src/cloudConsoleLauncher.ts
- src/cloudShellRunner.ts
upload playbook via azure storage file service.
- New Feature
> upload playbook via storage

- package.json
- src/cloudConsole.ts
- src/utilities.ts
bug fixing: when scp private key invalid, there's no error out.
- Bug fixing
> fix scp error when private key invalid, but no error out

- package.json
add ansible language for syntax highlighting per file association.
- New Feature
Issue #93
> add ansible language for syntax highlighting

- src/SSHConsole.ts
- src/SSHLauncher.ts
- src/interfaces.ts
- src/sshRunner.ts
- src/utilities.ts
support ssh passphrase
- New Feature
> support ssh passphrase

- src/sshRunner.ts
fix telemetry collecting in ssh
- Bug fixing
> fix telemetry in ssh

- README.md
- src/cloudShellRunner.ts
check azure account extension version.
- Bug fixing
> check azure account version

- CHANGELOG.md
- README.md
- src/sshRunner.ts
update doc for elease preparation.
- New Feature
> update doc for release preparation

- package.json
- src/cloudShellRunner.ts
- src/extension.ts
- src/utilities.ts
when user specify file.association in settings.json, to map yaml files to ansible language,  context menu to run playbooks will not be triggered. fix it.
- Bug fixing
> fix file association to ansible

- README.md
update doc to include cloudshell known issue.
- Bug fixing
> add cloudshell known issue in doc

- server/package-lock.json
- server/package.json
github report security vulnerability in request-light, update version
- Bug fixing
> update reqeust-light version

- package-lock.json
- package.json
update vscode-extension-telemetry version
- New Feature
- Bug fixing
> update vscode-extension-telemetry version

- src/utilities.ts
get workspace failed when file opened without workspace.
- Bug fixing
> fix bug when file open without workspace

- CHANGELOG.md
- package.json
update change log, prepare for 0.3.1 release.
- Bug fixing
> update changelog for 0.3.1

- README.md
- package.json
changed typo resuing to reusing
- Bug fixing
> typo: changed resuing to reusing

- README.md
- package.json
- server/package-lock.json
- server/package.json
- server/src/server.ts
- server/src/services/yamlHover.ts
- server/src/yamlLanguageService.ts
update language server to use redhat yaml language server, to leverage the yaml validation functionality.
- New Feature
> update language server

- server/package-lock.json
- server/package.json
fix missing dependencies
- Bug fixing
> fix missing dependencies

- src/cloudShellRunner.ts
- src/constants.ts
- src/fileSyncer.ts
- src/sshRunner.ts
bugs:
1. cloud shell, when user do signin for first time, 30 seconds timeout is not enough. so put sign in out of cloud shell logic.
2. cloud shell, when connection failed, cleanup terminal.
3. ssh, not copy when "no".
- Bug fixing
> fix bug found in bug bash

- CHANGELOG.md
- package.json
update changelog for 0.4.0 release preparation.
- Bug fixing
> update doc for 0.4.0 release

- README.md
- server/src/server.ts
- src/cloudShellRunner.ts
- src/sshRunner.ts
- src/utilities.ts
sometimes, you'll see below error when the extension activated:
```
[Error - 2:49:21 PM] Request textDocument/completion failed.
Message: Unhandled method textDocument/completion
Code: -32601 
```
It's from language server, but not related to functionality, but request-light bug, pls see here https://github.com/Microsoft/vscode/issues/39344, do same fix to resolve this.
- Bug fixing
> try fix language server error

- src/cloudShellRunner.ts
Updated a few strings that show up in notifications. Spoke with Catherine Zhu about these changes yesterday. Please let me know if there's anything else I need to do before these changes can be merged!
- Bug fixing
> Updated some notification strings

- README.md
fix some minor issues e.g. missing summary, typos etc.
> fix some minor typos

- server/.vscode/launch.json
- server/src/server.ts
- server/src/yamlLanguageService.ts
- src/ansibleCompletionItemProvider.ts
- syntaxes/Ansible.tmLanguage
> fix 181, 179

- src/constants.ts
- src/extension.ts
- src/fileSyncer.ts
- src/folderSyncer.ts
fix bug: config name in extension.ts is not correct.
- Bug fixing
> fix config name bug

- src/fileSyncer.ts
- src/utilities.ts
scp2 will not delete files exists on remote only when copying folder, workaround it.
- Bug fixing
> workarond scp not delete non-exisitng bug

- scripts/parse_ansible.py
update code snippets after 2.7 released.
- New Feature
> update 2.7 code snippet

- src/dockerRunner.ts
- src/utilities.ts
remove information about credential file in docker flow, which is annoying
- Bug fixing
> remove information about credential file in docker flow

- CHANGELOG.md
- package.json
> update doc and version for 0.5.2

- package-lock.json
- server/package-lock.json
fix security warning on security vulnerabilities .
- Bug fixing
> fix security warning

- src/azureHelpers.ts
- src/dockerRunner.ts
- src/restSamples.ts
- src/utilities.ts
> remove require out of functions

- src/ansibleCompletionItemProvider.ts
- src/dockerRunner.ts
remove useless regex for performance consideration.
- Bug fixing
> remove useless regex

- src/sshRunner.ts
when cd to targetfolder in ssh  scenario, fix  bug.
- Bug fixing
> fix cd to targetfolder

- src/SSHLauncher.ts
- src/completionData.ts
update  ansible code snippets for 2.8
- New Feature
> update code snippets for ansible 2.8

- .travis.yml
- appveyor.yml
- package-lock.json
- package.json
- server/package-lock.json
- server/package.json
- server/src/server.ts
- server/src/services/yamlHover.ts
- src/SSHLauncher.ts
upgrade dependencies version
- Bug fixing
> upgrade packages version

- .travis.yml
- package-lock.json
- package.json
- server/package-lock.json
- server/package.json
- src/test/extension.test.ts
update npm package versions
- Bug fixing
> update npm package versions
